version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3upload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1elvpadr379a5"
s3_prefix = "s3upload"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiName=\"s3upload\" StageName=\"v1\""
image_repositories = []
