AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ---
Parameters:
  ApiName:
    Description: API Gateway Name
    Type: String
  StageName:
    Description: v1
    Type: String
  S3BucketName:
    Description: Type of this BacketName.
    Type: String
    Default: fileupload
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref ApiName
      EndpointConfiguration: EDGE
      OpenApiVersion: 3.0.1
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.json
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}-${AWS::AccountId}
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: 's3:*'
          Effect: Allow
          Resource: 
            - !GetAtt 'S3Bucket.Arn'
            - !Sub '${S3Bucket.Arn}/*'
          Principal:
            AWS: 
              - "*"
Outputs:
  S3BucketName:
    Value: !Ref S3BucketName
